name: Publish Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        type: choice
        description: Release Type
        options:
          - stable
          - beta
          - alpha

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Java
        run: echo "JAVA_HOME=$JAVA_HOME_21_X64" >> "$GITHUB_ENV"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-home-cache-cleanup: true
          cache-read-only: true

      - name: Validate Gradle Wrapper Integrity
        uses: gradle/wrapper-validation-action@v4

      - name: make gradle wrapper executable
        run: chmod +x gradlew

      - name: Gradle Release Build
        env:
          RELEASE_WORKFLOW: true
        run: ./gradlew build

      - name: Set environment variables
        run: |
          echo "MINECRAFT_VERSION=$(./gradlew -q printMinecraftVersion)" >> $GITHUB_ENV
          echo "MOD_VERSION=$(./gradlew -q printModVersion)" >> $GITHUB_ENV
          echo "MIN_MINECRAFT_VERSION=$(./gradlew -q printMinMinecraftVersion)" >> $GITHUB_ENV
          echo "MAX_MINECRAFT_VERSION=$(./gradlew -q printMaxMinecraftVersion)" >> $GITHUB_ENV 
          echo "RELEASE_NAME=Rail Placement Fix $MOD_VERSION" >> $GITHUB_ENV


      - name: Replace placeholders in CHANGELOG.md
        run: |
          sed -i 's/_ReleaseTag_/${{ env.MOD_VERSION }}/g' CHANGELOG.md
          sed -i 's/_MCVersion_/${{ env.MINECRAFT_VERSION }}/g' CHANGELOG.md
          sed -i 's/_ModVersion_/${{ env.MOD_VERSION }}/g' CHANGELOG.md     
          sed -i 's/_MinMCVersion_/${{ env.MIN_MINECRAFT_VERSION }}/g' CHANGELOG.md
          sed -i 's/_MaxMCVersion_/${{ env.MAX_MINECRAFT_VERSION }}/g' CHANGELOG.md

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ env.MOD_VERSION }} \
            --title="${{ env.RELEASE_NAME }}" \
            --notes-file=CHANGELOG.md \
            --target=${{ github.ref_name }} \
            --draft=false \
            --prerelease=${{ inputs.releaseType != 'stable' }} \
            build/libs/*.jar

      - name: Build & Publish
        env:
          RELEASE_TYPE: ${{ inputs.releaseType }}
          MODRINTH_API_KEY: ${{ secrets.MODRINTH_API_KEY }}
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
        run: ./gradlew publishMods
